name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{https://api.render.com/deploy/srv-d87cmfbeo5us73e0ogj0?key=Zuid8JvYfFw}}"